# Generated by Django 4.2 on 2024-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_fichamedica_nombre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='id_especialidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='id_examen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
