# Generated by Django 4.2 on 2024-12-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_especialidades_id_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='rut_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medicos'),
        ),
    ]
