# Generated by Django 4.2 on 2024-12-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_fichamedica_rut_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='rut_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medicos'),
        ),
    ]
