# Generated by Django 4.2 on 2024-12-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_fichamedica_rut_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='id_examen',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='id_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.examenes'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.productos'),
        ),
    ]
